# Generated by Django 6.0.3 on 2026-04-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('1_project', 'AI Projects'), ('2_cert', 'Certificates'), ('3_social', 'Social Connect')], default='1_project', max_length=20)),
                ('icon_name', models.CharField(default='link', help_text='Lucide icon name (e.g., cpu, award, github)', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
