# Generated by Django 6.0.3 on 2026-04-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_link_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image_url',
            field=models.CharField(blank=True, help_text='URL or static path to banner image', max_length=500, null=True),
        ),
    ]
