# Generated by Django 6.0.3 on 2026-04-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_link_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload local photo/certificate (Overrides URL)', null=True, upload_to='previews/'),
        ),
    ]
