# Generated by Django 6.0.3 on 2026-04-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_link_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image',
        ),
    ]
